services:
  - type: web
    name: wattflex-core
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./voltwise-core/Dockerfile
    autoDeployTrigger: commit
    envVars:
      - {key: DB_URL, sync: false}
      - {key: DB_USER, sync: false}
      - {key: DB_PASSWORD, sync: false}
      - {key: KAFKA_BOOTSTRAP_SERVERS, sync: false}
      - {key: KAFKA_SECURITY_PROTOCOL, value: SASL_SSL}
      - {key: KAFKA_SASL_MECHANISM, value: PLAIN}
      - {key: KAFKA_SASL_JAAS_CONFIG, sync: false}
      - {key: KAFKA_ENABLED, value: "false"}
      - {key: JPA_DDL_AUTO, value: update}
      - {key: DEMO_DATA_ENABLED, value: "true"}
      - {key: DEMO_SENSOR_ENABLED, value: "true"}
      - {key: SENSOR_INTERVAL_MS, value: "3000"}
      - {key: GEMINI_API_KEY, sync: false}
      - {key: GEMINI_MODEL, value: gemini-3.5-flash}
      - {key: GROQ_API_KEY, sync: false}
      - {key: GROQ_MODEL, value: llama-3.3-70b-versatile}
      - {key: CORS_ALLOWED_ORIGINS, value: "https://*.vercel.app"}
